config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :invoices do
  	collection do
  		get :user
  	end
  end
  resources :charges
  resources :ra do
    collection do
      get :user_invoice
    end
  end
  resources :ras do
   collection do 
     get :ra_invoice
   end
  end
  resources :ra_comments
  resources :ras_comments
  resources :finance do
    collection do
      get :ras_invoice
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   # resources :carts
root 'invoices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/finance.rb
class Finance < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/ra.rb
class Ra < ApplicationRecord
end

app/models/ra_comment.rb
class RaComment < ApplicationRecord
	belongs_to :user
end

app/models/ras_comment.rb
class RasComment < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one :invoice
         has_one :ra_comment
         has_one :ras_comments
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :role, :name,  :is_active, :is_admin,:phone,:city,:address,:gender])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :role, :name, :is_active, :is_admin,:phone,:city,:address,:gender])
end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
def new
end
def index
	
	end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'usd',
  })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charges_path

end
end

app/controllers/finance_controller.rb
class FinanceController < ApplicationController
	def index
		@finance = User.where(role: "finance")
	end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
    if params[:id].present?
          @user = User.find(params[:user_id])
        end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def user
    @user = User.where(role: params[:role])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:title, :description, :deadline, :money, :total, :start_date, :end_date, :user_id)
    end
end

app/controllers/ra_comments_controller.rb
class RaCommentsController < ApplicationController
	def index
	end
	def create

		user_id = params[:ra_comments][:user_id]
		comment = params[:ra_comments][:comment]
		invoice_id = params[:ra_comments][:invoice_id]
		accept = params[:ra_comments][:accept]
		@ra_comment = RaComment.create(user_id: user_id, comment: comment, invoice_id: invoice_id, accept: accept)
		redirect_back(fallback_location: root_path)
		
	end

end

app/controllers/ra_controller.rb
class RaController < ApplicationController
	def index
		@ra = User.where(role: "ra")
	end
	def show
		@ra = User.where(role: "ra")
	end
	def user_invoice
		@user = User.find(params[:user_id])
	end
end

app/controllers/ras_comments_controller.rb
class RasCommentsController < ApplicationController
def index
	end
	def create

		user_id = params[:ras_comments][:user_id]
		comment = params[:ras_comments][:comment]
		invoice_id = params[:ras_comments][:invoice_id]
		accept = params[:ras_comments][:accept]
		@ras_comment = RasComment.create(user_id: user_id, comment: comment, invoice_id: invoice_id, accept: accept)
		redirect_back(fallback_location: root_path)
		
	end

end

app/controllers/ras_controller.rb
class RasController < ApplicationController
	def index
		@ras = User.where(role: "ras")
	end
	def show
		@ras = User.where(role: "ras")
    end

    def ra_invoice
		@user = User.find(params[:user_id])
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/finance_helper.rb
module FinanceHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/ra_helper.rb
module RaHelper
end

app/helpers/ras_comments_helper.rb
module RasCommentsHelper
end

app/helpers/ras_helper.rb
module RasHelper
end

app/views/ra/index.html.erb
<br><br><br><br>



 <table class=" myTable table table-hover">

  <thead>
    <th colspan="12" style="background-color:#5E1D55;color:white;"><h3>List of Referal Agents</h3></th>
  <tr style="background-color:#32A9EE;color:white;">
      <th>Name</th>
      <th>email</th>
      <th>Contact</th>
      <th>City</th>
      <th>Gender</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ra.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.city %></td>
        <td><%= user.gender %></td>
        <td><%= user.address %></td>
        <!-- <td><%#= user.try(:invoice).try(:title) %></td> -->

          <td><%= link_to 'Show Invoice',  user_invoice_ra_index_path(user_id: user.id), class: "btn btn-danger btn-lg btn-block btn-huge" %></td>
      </tr>
    <%end %>
  </tbody>
   </div>

</table>
<style type="text/css">
  .pricingTable:hover{
    margin-top: 10px;
}
</style>

app/views/ra/user_invoice.html.erb
<br><br><br><br>



 <table class=" myTable table table-hover">
  <thead>
<th colspan="8" style="background-color:#5E1D55;color:white;"><h3>Referal Agent`s Invoice</h3></th>
   <tr style="background-color:#32A9EE;color:white;">
    	<th>TITLE</th>
        <th>DESCRIPTION</th> 
        <th>DEADLINE</th>
        <th>MONEY</th>
        <th>TOTAL</th>
        <th>INVOICE DATE</th>
        <th></th>
        <th></th>
    </tr>
</thead>
</tr>
<body>
<tr>
<td><%= @user.try(:invoice).try(:title)%></td>
<td><%= @user.try(:invoice).try(:description)%></td>
<td><%= @user.try(:invoice).try(:deadline)%></td>
<td><%= @user.try(:invoice).try(:money)%></td>
<td><%= @user.try(:invoice).try(:total)%></td>
<td><%= @user.try(:invoice).try(:start_date)%><br></td>
</tr>
<td>
<% if current_user.role == "admin" || current_user.id == @user.id %>
<% if (RaComment.where(invoice_id: current_user.invoice.id).first.try(:accept)) == false  %>
<input class="xyz" type="button" name="name" value="Asigned to RAS" disabled="false">
<%else%>
<input class="abc " type="button" name="name" value="Asigned to RAS" >
<%end%>
            <% if RaComment.where(invoice_id: current_user.invoice.id).first.try(:invoice_id) == current_user.invoice.id && (RaComment.where(invoice_id: current_user.invoice.id).first.try(:accept)) == true  %>
           		 <h5>You Accept the invoice with comment</h5>
            <%else%>
         		<%= form_for :ra_comments, url: ra_comments_path, html: {class: "hidden-form"} do |f| %>
              		<%= f.collection_select :user_id, User.where(role: "ras").order(:name), :id, :name, include_blank: true,class: "form-control"%><br>
			            <%= f.text_area :comment, placeholder: "Enter Comment" %><br>
			            <%= f.hidden_field :invoice_id, value: @user.try(:invoice).try(:id) %>
			            <%= f.hidden_field :accept,value: true %>
			            <%= f.submit "Send Comment",class: "btn btn-success", name: "nm"%>
			    <%end%>
         <%end%> 
<% end %>
</td>
</body>
<td>
<% if current_user.role == "admin" || current_user.id == @user.id %>
<% if (RaComment.where(invoice_id: current_user.invoice.id).first.try(:accept)) == true  %>
	<input class="xyz" type="button" name="name" value="Reject" disabled="true">
	<%else%>
		<input class="xyz"  type="button" name="name" value="Reject">
	<%end%>

	   <% if RaComment.where(invoice_id: current_user.invoice.id).first.try(:invoice_id) == current_user.invoice.id && (RaComment.where(invoice_id: current_user.invoice.id).first.try(:accept)) == false  %>
           		 <h5>Invoice has been Rejected!</h5>
            <%else%>
         		<%= form_for :ra_comments, url: ra_comments_path, html: {class: "hidden-form"} do |f| %>
              		<%= f.collection_select :user_id, User.where(role: "ras").order(:name), :id, :name, include_blank: true,class: "form-control"%><br>
			            <%= f.text_area :comment, placeholder: "Enter Comment" %><br>
			            <%= f.hidden_field :invoice_id, value: @user.try(:invoice).try(:id) %>
			             <%= f.hidden_field :accept,value: false %>
			            <%= f.submit "Send Comment",class: "btn btn-success", name: "nm"%>
			    <%end%>
         <%end%> 
	<% end %>
</td>


<style type="text/css">
.abc{
 float:left;
  list-style:none;
}
.xyz{
	background-color: #ff0000;
}
.abc{
	background-color: #8af103;
}
.hidden-form{
  visibility:hidden;
  }
.show-form{
visibility: visible !important;
}
</style>
<script type="text/javascript">
   $('.abc').click(function(){
$(this).next().toggleClass('show-form');
});
   $('.xyz').click(function(){
$(this).next().toggleClass('show-form');
});
</script> 

app/views/ras/index.html.erb
<br><br><br><br>
<table class=" myTable table table-hover">
  <thead>
    <th colspan="8" style="background-color:#5E1D55;color:white;"><h3>List of Referal Agents</h3></th>
  <tr style="background-color:#32A9EE;color:white;">
      <th>Name</th>
      <th>email</th>
      <th>Contact</th>
      <th>City</th>
      <th>Gender</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ras.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.city %></td>
        <td><%= user.gender %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show Invoice',  ra_invoice_ras_path(user_id: user.id), class: "btn btn-danger btn-lg btn-block btn-huge" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ras/ra_invoice.html.erb
<br><br><br><br>
<table class=" myTable table table-hover">
<thead>
  <th colspan="8" style="background-color:#5E1D55;color:white;">
    <h3>Referal Agent`s Invoice</h3>
  </th>
  <tr style="background-color:#32A9EE;color:white;">
    <th>TITLE</th>
    <th>DESCRIPTION</th>
    <th>DEADLINE</th>
    <th>MONEY</th>
    <th>TOTAL</th>
    <th>INVOICE DATE</th>
    <th>Comment</th>
    <th></th>
    <th></th>
  </tr>
</thead>
</tr>
<tr>
  <%invoice_id = RaComment.where(user_id: params[:user_id]).first.try(:invoice_id)
    if invoice_id
        @invoice = Invoice.find(invoice_id)
       @comment = RaComment.where(invoice_id:  @invoice.id).first.comment
     end
     %>
  <% if invoice_id %>
  <td><%= @invoice.try(:title)%></td>
  <td><%= @invoice.try(:description)%></td>
  <td><%= @invoice.try(:deadline)%></td>
  <td><%= @invoice.try(:money)%></td>
  <td><%= @invoice.try(:total)%></td>
  <td><%= @invoice.try(:start_date)%><br></td>
  <td><%= @comment %><br></td>
  <% else %>
  <% end %>
</tr>
<td>
  <% if current_user.role == "admin" || current_user.id == @user.id %>
  <% if (RasComment.where(invoice_id: @invoice).first.try(:accept)) == true  %>
  <input class="xyz" type="button" name="name" value="Assign to finance" disabled="true">
  <%else%>    
  <input class="xyz"  type="button" name="name" value="Assign to finance">
  <%end%>
  <% if RasComment.where(invoice_id: @ivoice).first.try(:invoice_id) == @invoice && (RaComment.where(invoice_id: @invoice).first.try(:accept)) == false  %>
  <h5>Invoice has been Rejected!</h5>
  <%else%>
  <%= form_for :ras_comments, url: ras_comments_path, html: {class: "hidden-form"} do |f| %>
  <%= f.collection_select :user_id, User.where(role: "finance").order(:name), :id, :name, include_blank: true,class: "form-control"%><br>
  <%= f.text_area :comment, placeholder: "Enter Comment" %><br>
  <%= f.hidden_field :invoice_id, value: @user.try(:invoice).try(:id) %>
  <%= f.hidden_field :accept,value: true %>
  <%= f.submit "Send Comment",class: "btn btn-success", name: "nm"%>
  <%end%>
  <%end%> 
  <% end %>
</td>
<style type="text/css">
  .abc{
  float:left;
  list-style:none;
  }
  .xyz{
  background-color: #ff0000;
  }
  .abc{
  background-color: #8af103;
  }
  .hidden-form{
  visibility:hidden;
  }
  .show-form{
  visibility: visible !important;
  }
</style>
<script type="text/javascript">
  $('.abc').click(function(){
  $(this).next().toggleClass('show-form');
  });
  $('.xyz').click(function(){
  $(this).next().toggleClass('show-form');
  });
</script>

app/views/ras/show.html.erb
<br><br><br><br><br><br>
<p id="notice"><%= notice %></p>
<div class="container"><p>
  <strong>Title:</strong>
  <%= @invoice.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @invoice.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @invoice.deadline %>
</p>

<p>
  <strong>Money:</strong>
  <%= @invoice.money %>
</p>

<p>
  <strong>Total:</strong>
  <%= @invoice.total %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @invoice.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @invoice.end_date %>
</p>