config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :invoices do
  	collection do
  		get :user
  	end
  end
  resources :charges
  resources :ra do
    collection do
      get :user_invoice
    end
  end
  resources :ras do
   collection do 
     get :ra_invoice
   end
  end
  resources :ra_comments
  resources :ras_comments
  resources :finance do
    collection do
      get :ras_invoice
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   # resources :carts
root 'invoices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/finance.rb
class Finance < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/ra.rb
class Ra < ApplicationRecord
end

app/models/ra_comment.rb
class RaComment < ApplicationRecord
	belongs_to :user
end

app/models/ras_comment.rb
class RasComment < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one :invoice
         has_one :ra_comment
         has_one :ras_comments
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :role, :name,  :is_active, :is_admin,:phone,:city,:address,:gender])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :role, :name, :is_active, :is_admin,:phone,:city,:address,:gender])
end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
def new
end
def index
	
	end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'usd',
  })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charges_path

end
end

app/controllers/finance_controller.rb
class FinanceController < ApplicationController
	def index
		@finance = User.where(role: "finance")
	end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
    if params[:id].present?
          @user = User.find(params[:user_id])
        end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def user
    @user = User.where(role: params[:role])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:title, :description, :deadline, :money, :total, :start_date, :end_date, :user_id)
    end
end

app/controllers/ra_controller.rb
class RaController < ApplicationController
	def index
		@ra = User.where(role: "ra")
	end
	def show
		@ra = User.where(role: "ra")
	end
	def user_invoice
		@user = User.find(params[:user_id])
	end
end

app/controllers/ras_controller.rb
class RasController < ApplicationController
	def index
		@ras = User.where(role: "ras")
	end
	def show
		@ras = User.where(role: "ras")
    end

    def ra_invoice
		@user = User.find(params[:user_id])
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/finance_helper.rb
module FinanceHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/ra_helper.rb
module RaHelper
end

app/helpers/ras_comments_helper.rb
module RasCommentsHelper
end

app/helpers/ras_helper.rb
module RasHelper
end

app/views/finance/index.html.erb
<br><br><br><br>
 <table class=" myTable table table-hover">
  <thead>
    <th colspan="8" style="background-color:#5E1D55;color:white;"><h3>List of Finance Teams</h3></th>
  <tr style="background-color:#32A9EE;color:white;">
      <th>Name</th>
      <th>email</th>
      <th>Contact</th>
      <th>City</th>
      <th>Gender</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finance.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.city %></td>
        <td><%= user.gender %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show Invoice',  ras_invoice_finance_path(user_id: user.id), class: "btn btn-danger btn-lg btn-block btn-huge" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/finance/ras_invoice.html.erb
ras_invoice.html.erb

app/views/finance/show.html.erb
show.html.erb

app/views/invoices/_form.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br><br><br><br>
<div class="container">
       <table class="table table-striped">
          <tbody>
             <tr>
                <td colspan="1">
                   <form class="well form-horizontal">
                      <fieldset>
                         <div class="form-group">
                            <label class="col-md-4 control-label">Title</label>
                            <div class="col-md-8 inputGroupContainer">
                               <div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span><%= form.text_field :title, class: "form-control" %></div>
                            </div>
                         </div>
                          <div class="form-group">
                            <label class="col-md-4 control-label">Description</label>
                            <div class="col-md-8 inputGroupContainer">
                               <div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-tasks"></i></span><%= form.text_field :description, class: "form-control" %></div>
                             </div>
                           </div>

                                <div class="form-group">
                            <label class="col-md-4 control-label">Deadline</label>
                            <div class="col-md-8 inputGroupContainer">
                               <div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-bullhorn"></i></span><%= form.text_field :deadline, class: "form-control" %></div>
                             </div></div>
                               <div class="form-group">
                            <label class="col-md-4 control-label">Money</label>
                            <div class="col-md-8 inputGroupContainer">
                               <div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-usd"></i></span><%= form.text_field :money, class: "form-control" %></div></div></div>
                               <div class="form-group">
                            <label class="col-md-4 control-label">Total</label>
                            <div class="col-md-8 inputGroupContainer">
                               <div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-asterisk"></i></span><%= form.text_field :total, class: "form-control" %></div></div></div>
                               <div class="form-group">
                            <label class="col-md-4 control-label">Start Date</label>
                            <div class="col-md-8 inputGroupContainer">
                               <div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-eye-open"></i></span><%= form.text_field :start_date, class: "form-control" %></div></div></div>
                               <div class="form-group">
                            <label class="col-md-4 control-label">End Date</label>
                            <div class="col-md-8 inputGroupContainer">
                               <div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-eye-close"></i></span><%= form.text_field :end_date, class: "form-control" %></div>
                             </div>
                             </div>
                               <div class="field">
                                <select id="role">
                                  <option value="">Select Role</option>
                                  <option value="ra">RA</option>
                                  <option value="ras">RAS</option>
                                </select>
                              </div>
                                <div class="sub">
                                <%#= form.label :user_id %><br />
                                <%#= form.collection_select :user_id, User.order(:name), :id, :name, include_blank: true,class: "form-control"%>
                              </div>

                                <div class="actions" class="btn btn-danger">
                                  <%= form.submit%>
                                </div>
                       </fieldset>
                     </form>
                   </td>
                 </tr>
               </tbody>
             </table>
           </div>
  <% end %>
  <script type="text/javascript">
    $('#role').on('change',function()
    {
     var cat = this.value
     $.ajax({
      url: '/invoices/user',
      type: 'GET',
      datatype: "script",
      data: {role: cat}
     }) 
    });
  </script>

app/views/invoices/_user.html.erb
 <div class="sub">
  <select class="selectbox_date TW260 marR10" name="invoice[user_id]" id="user">
    <option value="">-- User--</option>
    <% for subcat in @user %>
        <option value="<%= subcat[:id] %>"><%= subcat[:name] %></option>
    <% end %>
</select>
</div>

app/views/invoices/edit.html.erb
<br><br><br><br>

<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path, class: "btn btn-danger" %>

app/views/invoices/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<br><br><br><br>
 <table class=" myTable table table-hover">
  <thead>
    <th colspan="12" style="background-color:#5E1D55;color:white;"><h3>List of Invoices</h3></th>
  <tr style="background-color:#32A9EE;color:white;">
      <th>Title</th>
      <th>Description</th>
      <th>Deadline</th>
      <th>Money</th>
      <th>Total</th>
      <th>Start date</th>
      <th>End date</th>
      <th>User Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.title %></td>
        <td><%= invoice.description %></td>
        <td><%= invoice.deadline %></td>
        <td><%= invoice.money %></td>
        <td><%= invoice.total %></td>
        <td><%= invoice.start_date %></td>
        <td><%= invoice.end_date %></td>
        <%#byebug%>
        <td><%= invoice.user.try(:name)%></td>
        <td><%= link_to 'Show', invoice, class: "btn btn-3" %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice),class: "btn btn-2" %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?'},class: "btn btn-1" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path,class: "btn btn-4" %>

<style type="text/css">
  body{
  font-family: 'Montserrat', sans-serif;
  margin:0;
}

.container {
  display: flex;
  justify-content: center;
  align-items: center;
  align-content: center;
  flex-wrap: wrap;
  width: 80vw;
  margin: 0 auto;
  min-height: 100vh;
}
.btn {
  flex: 1 1 auto;
  margin: 10px;
  padding: 10px;
  text-align: center;
  text-transform: uppercase;
  transition: 0.2s;
  background-size: 50% auto;
  color: white;
 /* text-shadow: 0px 0px 10px rgba(0,0,0,0.2);*/
  box-shadow: 0 0 20px #eee;
  border-radius: 10px;
 }

/* Demo Stuff End -> */

/* <- Magic Stuff Start */

.btn:hover {
  background-position: right center; /* change the direction of the change here */
}

.btn-1 {
  background-image: linear-gradient(to right, #597994 0%, #d83405 51%, #fb1515 100%);
}

.btn-2 {
  background-image: linear-gradient(to right, #fbc2eb 0%, #a6c1ee 51%, #fbc2eb 100%);
}

.btn-3 {
  background-image: linear-gradient(to right, #84fab0 0%, #0a4a69 51%, #84fab0 100%);
}

.btn-4 {
  background-image: linear-gradient(to right, #a1c4fd 0%, #006492 51%, #a1c4fd 100%);
}

.btn-5 {
  background-image: linear-gradient(to right, #ffecd2 0%, #fcb69f 51%, #ffecd2 100%);
}

/* Magic Stuff End -> */
</style>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path,class: "btn btn-danger" %>

app/views/invoices/show.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<br><br><br><br>

    <table class="table stats caps">
      <thead>
 <tr style="background:#e73a3f;color:#e6f0f9; border-radius:6px;">
  <th>Title:</th>
  <th>Description:</th>
  <th>Deadline:</th>
  <th>Money:</th>
  <th>Total:</th>
  <th>Start date:</th>
  <th>End date:</th>
  
</tr>
</thead>
<tbody>
  <tr>
    <td><%= @invoice.title %></td>
    <td><%= @invoice.description %></td>
    <td><%= @invoice.deadline %></td>
    <td> <%= @invoice.money %></td>
    <td><%= @invoice.total %></td>
    <td><%= @invoice.start_date %></td>
    <td><%= @invoice.end_date %></td>
  </tr>
</tbody>
</div>
</table>
<%= link_to 'Edit', edit_invoice_path(@invoice), class: ""%> |
<%= link_to 'Back', invoices_path,class: "" %>

<%#= link_to 'Order', charges_new_path%>
<a class="btn btn-danger btn-lg btn-block btn-huge" href="/charges/new">Place Order</a>

<style type="text/css">
  btn-huge{
    padding-top:20px;
    padding-bottom:20px;
}

.btn-block {
    display: block;
    width: 15%;
}
</style>

app/views/invoices/user.js.erb
$('.sub').html('<%= j render "user"%>'); 